Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [16]:
import numpy as np

def gen_vander_matrix(input_matrix, n, increasing=False):
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in input_matrix for i in range(n)]).reshape(input_matrix.size,n)
        
    elif increasing:
        op_matx = np.array([x**i for x in input_matrix for i in range(n)]).reshape(input_matrix.size,n)
    
    return op_matx

input_matrix=np.array([1,2,3,4,5])
num_col_opmat=4
print("input matrix-",input_matrix)
print("Number of columns in output matrix:",num_col_opmat,"\n")
op_matrix_descendng=gen_vander_matrix(input_matrix,num_col_opmat,False)
print("Matrix when increasing arguement is False :\n",op_matrix_descendng)


op_matrix_ascending=gen_vander_matrix(input_matrix,num_col_opmat,True)
print("Matrix when increasing arguement is True :\n",op_matrix_ascending)


input matrix- [1 2 3 4 5]
Number of columns in output matrix: 4 

Matrix when increasing arguement is False :
 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]
Matrix when increasing arguement is True :
 [[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]


2.Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [15]:

def gen_moving_avg(input_matrix,window):     
    return np.array([np.sum(input_matrix[i:i+window])/window for i in range(input_matrix.size - window +1)])
        

input_array=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
window=3
print("Moving average array for the given array with window size {} are \n{}-".format(window,gen_moving_avg(input_array,window)))

Moving average array for the given array with window size 3 are 
[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]-
